name: "Build"

on:
  push:
    paths:
      - 'firebase/**'
    branches:
      - main  
  
jobs:
  Firebase:
    runs-on: ubuntu-latest
    name: Firebase

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: firebase
          file: firebase/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/firebase:10-alpine_${{ github.run_number }}