name: "Build"

on:
  push:
    paths:
      - 'git-sftp/**'
    branches:
      - main  
  
jobs:
  Ansible:
    runs-on: ubuntu-latest
    name: GIT-SFTP

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ansible
          file: ansible/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/git-sftp:alpine-3.15-7.81.0_${{ github.run_number }}